# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import spellingb_pb2 as spellingb__pb2


class SpellingBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/distributed.SpellingB/StartGame',
                request_serializer=spellingb__pb2.GameRequest.SerializeToString,
                response_deserializer=spellingb__pb2.GameResponse.FromString,
                )
        self.VerifyWord = channel.unary_unary(
                '/distributed.SpellingB/VerifyWord',
                request_serializer=spellingb__pb2.WordRequest.SerializeToString,
                response_deserializer=spellingb__pb2.WordResponse.FromString,
                )
        self.ReturnPoints = channel.unary_unary(
                '/distributed.SpellingB/ReturnPoints',
                request_serializer=spellingb__pb2.PointsRequest.SerializeToString,
                response_deserializer=spellingb__pb2.PointsResponse.FromString,
                )


class SpellingBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpellingBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=spellingb__pb2.GameRequest.FromString,
                    response_serializer=spellingb__pb2.GameResponse.SerializeToString,
            ),
            'VerifyWord': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyWord,
                    request_deserializer=spellingb__pb2.WordRequest.FromString,
                    response_serializer=spellingb__pb2.WordResponse.SerializeToString,
            ),
            'ReturnPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnPoints,
                    request_deserializer=spellingb__pb2.PointsRequest.FromString,
                    response_serializer=spellingb__pb2.PointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.SpellingB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpellingB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed.SpellingB/StartGame',
            spellingb__pb2.GameRequest.SerializeToString,
            spellingb__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed.SpellingB/VerifyWord',
            spellingb__pb2.WordRequest.SerializeToString,
            spellingb__pb2.WordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReturnPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed.SpellingB/ReturnPoints',
            spellingb__pb2.PointsRequest.SerializeToString,
            spellingb__pb2.PointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
