# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spellingb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spellingb.proto',
  package='distributed',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fspellingb.proto\x12\x0b\x64istributed\"\r\n\x0bGameRequest\"7\n\x0cGameResponse\x12\x0f\n\x07pangram\x18\x01 \x01(\t\x12\x16\n\x0erequiredLetter\x18\x02 \x01(\t\"\x1b\n\x0bWordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"\x1e\n\x0cWordResponse\x12\x0e\n\x06isWord\x18\x01 \x01(\x08\"\x0f\n\rPointsRequest\" \n\x0ePointsResponse\x12\x0e\n\x06points\x18\x01 \x01(\x05\x32\xdf\x01\n\tSpellingB\x12\x42\n\tStartGame\x12\x18.distributed.GameRequest\x1a\x19.distributed.GameResponse\"\x00\x12\x43\n\nVerifyWord\x12\x18.distributed.WordRequest\x1a\x19.distributed.WordResponse\"\x00\x12I\n\x0cReturnPoints\x12\x1a.distributed.PointsRequest\x1a\x1b.distributed.PointsResponse\"\x00\x62\x06proto3'
)




_GAMEREQUEST = _descriptor.Descriptor(
  name='GameRequest',
  full_name='distributed.GameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=45,
)


_GAMERESPONSE = _descriptor.Descriptor(
  name='GameResponse',
  full_name='distributed.GameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pangram', full_name='distributed.GameResponse.pangram', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requiredLetter', full_name='distributed.GameResponse.requiredLetter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=102,
)


_WORDREQUEST = _descriptor.Descriptor(
  name='WordRequest',
  full_name='distributed.WordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='distributed.WordRequest.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=131,
)


_WORDRESPONSE = _descriptor.Descriptor(
  name='WordResponse',
  full_name='distributed.WordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isWord', full_name='distributed.WordResponse.isWord', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=163,
)


_POINTSREQUEST = _descriptor.Descriptor(
  name='PointsRequest',
  full_name='distributed.PointsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=180,
)


_POINTSRESPONSE = _descriptor.Descriptor(
  name='PointsResponse',
  full_name='distributed.PointsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='distributed.PointsResponse.points', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['GameRequest'] = _GAMEREQUEST
DESCRIPTOR.message_types_by_name['GameResponse'] = _GAMERESPONSE
DESCRIPTOR.message_types_by_name['WordRequest'] = _WORDREQUEST
DESCRIPTOR.message_types_by_name['WordResponse'] = _WORDRESPONSE
DESCRIPTOR.message_types_by_name['PointsRequest'] = _POINTSREQUEST
DESCRIPTOR.message_types_by_name['PointsResponse'] = _POINTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameRequest = _reflection.GeneratedProtocolMessageType('GameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEREQUEST,
  '__module__' : 'spellingb_pb2'
  # @@protoc_insertion_point(class_scope:distributed.GameRequest)
  })
_sym_db.RegisterMessage(GameRequest)

GameResponse = _reflection.GeneratedProtocolMessageType('GameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMERESPONSE,
  '__module__' : 'spellingb_pb2'
  # @@protoc_insertion_point(class_scope:distributed.GameResponse)
  })
_sym_db.RegisterMessage(GameResponse)

WordRequest = _reflection.GeneratedProtocolMessageType('WordRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORDREQUEST,
  '__module__' : 'spellingb_pb2'
  # @@protoc_insertion_point(class_scope:distributed.WordRequest)
  })
_sym_db.RegisterMessage(WordRequest)

WordResponse = _reflection.GeneratedProtocolMessageType('WordResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORDRESPONSE,
  '__module__' : 'spellingb_pb2'
  # @@protoc_insertion_point(class_scope:distributed.WordResponse)
  })
_sym_db.RegisterMessage(WordResponse)

PointsRequest = _reflection.GeneratedProtocolMessageType('PointsRequest', (_message.Message,), {
  'DESCRIPTOR' : _POINTSREQUEST,
  '__module__' : 'spellingb_pb2'
  # @@protoc_insertion_point(class_scope:distributed.PointsRequest)
  })
_sym_db.RegisterMessage(PointsRequest)

PointsResponse = _reflection.GeneratedProtocolMessageType('PointsResponse', (_message.Message,), {
  'DESCRIPTOR' : _POINTSRESPONSE,
  '__module__' : 'spellingb_pb2'
  # @@protoc_insertion_point(class_scope:distributed.PointsResponse)
  })
_sym_db.RegisterMessage(PointsResponse)



_SPELLINGB = _descriptor.ServiceDescriptor(
  name='SpellingB',
  full_name='distributed.SpellingB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=217,
  serialized_end=440,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartGame',
    full_name='distributed.SpellingB.StartGame',
    index=0,
    containing_service=None,
    input_type=_GAMEREQUEST,
    output_type=_GAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VerifyWord',
    full_name='distributed.SpellingB.VerifyWord',
    index=1,
    containing_service=None,
    input_type=_WORDREQUEST,
    output_type=_WORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnPoints',
    full_name='distributed.SpellingB.ReturnPoints',
    index=2,
    containing_service=None,
    input_type=_POINTSREQUEST,
    output_type=_POINTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPELLINGB)

DESCRIPTOR.services_by_name['SpellingB'] = _SPELLINGB

# @@protoc_insertion_point(module_scope)
